import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import {
  DynamoDBDocumentClient,
  GetCommand,
  PutCommand,
  UpdateCommand,
} from '@aws-sdk/lib-dynamodb';
import { AuthConfigurationError, getGoogleAuthConfig } from '../auth/config.js';
import { recordAccessEvent } from '../auth/audit.js';
import { verifyAtlasSessionCookie, type AtlasSessionClaims } from '../auth/session.js';
import type { CorporateIdentity } from '../auth/oidc.js';

/**
 * AtlasProfile — Canonical corporate profile stored by stable identity subject.
 *
 * The profile is created during verified login, is resolved by `subject` rather
 * than email, and exposes only presentation fields to the owning person. Role,
 * status and corporate identity remain server-managed for later governance slices.
 */
export type ProfileRole = 'administrative' | 'developer' | 'superadmin';
export type ProfileStatus = 'active' | 'inactive';

export interface AtlasProfile {
  subject: string;
  email: string;
  displayName: string;
  picture?: string;
  description: string;
  role: ProfileRole;
  status: ProfileStatus;
  onboardingPending: boolean;
}

interface StoredProfile extends AtlasProfile {
  pk: string;
  sk: string;
  entity: 'profile';
  createdAt: string;
  updatedAt: string;
}

/** Allowlisted fields accepted by the self-service profile endpoint. */
export interface ProfilePatch {
  displayName?: unknown;
  picture?: unknown;
  description?: unknown;
  onboardingPending?: unknown;
}

/** Signals a safe HTTP error while resolving or mutating a profile. */
export class ProfileRequestError extends Error {
  constructor(
    public readonly statusCode: 400 | 401 | 403 | 404 | 503,
    public readonly code: string,
    message: string,
  ) {
    super(message);
    this.name = 'ProfileRequestError';
  }
}

interface ProfileRequestEvent {
  headers?: Record<string, string | undefined>;
  cookies?: string[];
}

interface ProfileResolution {
  profile: AtlasProfile;
  session: AtlasSessionClaims;
}

const localProfiles = new Map<string, StoredProfile>();

/** Returns the linked Profiles table name generated by SST, if available. */
function getLinkedProfilesTableName(): string | undefined {
  const rawResource = process.env.SST_RESOURCE_Profiles;
  if (!rawResource) return undefined;

  try {
    const resource = JSON.parse(rawResource) as { tableName?: unknown };
    return typeof resource.tableName === 'string' && resource.tableName.length > 0
      ? resource.tableName
      : undefined;
  } catch {
    return undefined;
  }
}

/** Creates the shared DynamoDB document client for profile operations. */
function getDocumentClient(): DynamoDBDocumentClient {
  return DynamoDBDocumentClient.from(new DynamoDBClient({}));
}

/** Converts a DynamoDB record into the public profile contract. */
function toPublicProfile(profile: StoredProfile): AtlasProfile {
  return {
    subject: profile.subject,
    email: profile.email,
    displayName: profile.displayName,
    picture: profile.picture,
    description: profile.description,
    role: profile.role,
    status: profile.status,
    onboardingPending: profile.onboardingPending,
  };
}

/** Builds the first profile with the least-privileged role and pending onboarding. */
function createInitialProfile(identity: CorporateIdentity, timestamp: string): StoredProfile {
  return {
    pk: `PROFILE#${identity.subject}`,
    sk: 'PROFILE',
    entity: 'profile',
    subject: identity.subject,
    email: identity.email,
    displayName: identity.name?.trim() || identity.email,
    picture: identity.picture,
    description: '',
    role: 'administrative',
    status: 'active',
    onboardingPending: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  };
}

/** Reads one profile by stable subject with a strongly consistent lookup. */
export async function getProfileBySubject(subject: string): Promise<AtlasProfile | undefined> {
  const tableName = getLinkedProfilesTableName();
  if (!tableName) {
    const localProfile = localProfiles.get(subject);
    return localProfile ? toPublicProfile(localProfile) : undefined;
  }

  const result = await getDocumentClient().send(new GetCommand({
    TableName: tableName,
    Key: { pk: `PROFILE#${subject}`, sk: 'PROFILE' },
    ConsistentRead: true,
  }));
  const item = result.Item as StoredProfile | undefined;
  return item?.entity === 'profile' ? toPublicProfile(item) : undefined;
}

/** Reads the stored record needed by internal updates. */
async function getStoredProfileBySubject(subject: string): Promise<StoredProfile | undefined> {
  const tableName = getLinkedProfilesTableName();
  if (!tableName) return localProfiles.get(subject);

  const result = await getDocumentClient().send(new GetCommand({
    TableName: tableName,
    Key: { pk: `PROFILE#${subject}`, sk: 'PROFILE' },
    ConsistentRead: true,
  }));
  const item = result.Item as StoredProfile | undefined;
  return item?.entity === 'profile' ? item : undefined;
}

/**
 * Gets or conditionally creates a profile for a verified identity.
 *
 * The conditional write makes concurrent first logins converge on one profile;
 * a losing request rereads the existing subject-keyed record instead of creating
 * a second identity. Email is synchronized as mutable contact data only.
 */
export async function getOrCreateProfile(identity: CorporateIdentity): Promise<{
  profile: AtlasProfile;
  created: boolean;
}> {
  const existing = await getStoredProfileBySubject(identity.subject);
  if (existing) {
    const profile = await synchronizeContactEmail(existing, identity.email);
    return { profile: toPublicProfile(profile), created: false };
  }

  const timestamp = new Date().toISOString();
  const initialProfile = createInitialProfile(identity, timestamp);
  const tableName = getLinkedProfilesTableName();
  if (!tableName) {
    localProfiles.set(identity.subject, initialProfile);
    return { profile: toPublicProfile(initialProfile), created: true };
  }

  try {
    await getDocumentClient().send(new PutCommand({
      TableName: tableName,
      Item: initialProfile,
      ConditionExpression: 'attribute_not_exists(pk)',
    }));
    return { profile: toPublicProfile(initialProfile), created: true };
  } catch (error) {
    // Guard: a concurrent login already owns this subject; reuse its canonical profile.
    if (!(error instanceof Error) || error.name !== 'ConditionalCheckFailedException') throw error;
    const concurrentProfile = await getStoredProfileBySubject(identity.subject);
    if (!concurrentProfile) throw error;
    return {
      profile: toPublicProfile(await synchronizeContactEmail(concurrentProfile, identity.email)),
      created: false,
    };
  }
}

/** Updates only the mutable contact email after a verified provider login. */
async function synchronizeContactEmail(profile: StoredProfile, email: string): Promise<StoredProfile> {
  if (profile.email === email) return profile;
  const updatedAt = new Date().toISOString();
  const updatedProfile = { ...profile, email, updatedAt };
  const tableName = getLinkedProfilesTableName();
  if (!tableName) {
    localProfiles.set(profile.subject, updatedProfile);
    return updatedProfile;
  }

  const result = await getDocumentClient().send(new UpdateCommand({
    TableName: tableName,
    Key: { pk: profile.pk, sk: profile.sk },
    UpdateExpression: 'SET #email = :email, #updatedAt = :updatedAt',
    ExpressionAttributeNames: { '#email': 'email', '#updatedAt': 'updatedAt' },
    ExpressionAttributeValues: { ':email': email, ':updatedAt': updatedAt },
    ReturnValues: 'ALL_NEW',
  }));
  return result.Attributes as StoredProfile;
}

/** Validates and normalizes the client allowlist without trusting protected fields. */
function validateProfilePatch(input: unknown): {
  displayName?: string;
  picture?: string | null;
  description?: string;
  onboardingPending?: false;
} {
  if (!input || typeof input !== 'object' || Array.isArray(input)) {
    throw new ProfileRequestError(400, 'INVALID_PROFILE_BODY', 'Profile body is invalid');
  }

  const body = input as ProfilePatch;
  const allowedFields = new Set(['displayName', 'picture', 'description', 'onboardingPending']);
  const receivedFields = Object.keys(body);
  if (receivedFields.some((field) => !allowedFields.has(field))) {
    throw new ProfileRequestError(400, 'PROTECTED_PROFILE_FIELD', 'Profile contains a protected field');
  }

  const patch: {
    displayName?: string;
    picture?: string | null;
    description?: string;
    onboardingPending?: false;
  } = {};

  if ('displayName' in body) {
    if (typeof body.displayName !== 'string') {
      throw new ProfileRequestError(400, 'INVALID_DISPLAY_NAME', 'Display name is invalid');
    }
    const displayName = body.displayName.trim();
    if (displayName.length < 1 || displayName.length > 80) {
      throw new ProfileRequestError(400, 'INVALID_DISPLAY_NAME', 'Display name is invalid');
    }
    patch.displayName = displayName;
  }

  if ('description' in body) {
    if (typeof body.description !== 'string' || body.description.trim().length > 240) {
      throw new ProfileRequestError(400, 'INVALID_DESCRIPTION', 'Description is invalid');
    }
    patch.description = body.description.trim();
  }

  if ('picture' in body) {
    if (body.picture === null || body.picture === '') {
      patch.picture = null;
    } else if (typeof body.picture !== 'string' || body.picture.length > 2048) {
      throw new ProfileRequestError(400, 'INVALID_PICTURE', 'Picture URL is invalid');
    } else {
      let pictureUrl: URL;
      try {
        pictureUrl = new URL(body.picture.trim());
      } catch {
        throw new ProfileRequestError(400, 'INVALID_PICTURE', 'Picture URL is invalid');
      }
      if (pictureUrl.protocol !== 'https:') {
        throw new ProfileRequestError(400, 'INVALID_PICTURE', 'Picture URL is invalid');
      }
      patch.picture = pictureUrl.toString();
    }
  }

  if ('onboardingPending' in body) {
    if (body.onboardingPending !== false) {
      throw new ProfileRequestError(400, 'INVALID_ONBOARDING_STATE', 'Onboarding state is invalid');
    }
    patch.onboardingPending = false;
  }

  if (Object.keys(patch).length === 0) {
    throw new ProfileRequestError(400, 'EMPTY_PROFILE_UPDATE', 'Profile update is empty');
  }
  return patch;
}

/**
 * Updates presentation fields and completes onboarding idempotently.
 *
 * The DynamoDB update is deliberately a single conditional write so a concurrent
 * profile deactivation cannot leave a partial self-service mutation behind.
 */
export async function updateOwnProfile(subject: string, input: unknown): Promise<AtlasProfile> {
  const patch = validateProfilePatch(input);
  const current = await getStoredProfileBySubject(subject);
  if (!current) throw new ProfileRequestError(404, 'PROFILE_NOT_FOUND', 'Profile not found');
  if (current.status !== 'active') throw new ProfileRequestError(403, 'PROFILE_INACTIVE', 'Profile is inactive');

  const updatedAt = new Date().toISOString();
  const updatedProfile: StoredProfile = {
    ...current,
    ...(patch.displayName === undefined ? {} : { displayName: patch.displayName }),
    ...(patch.picture === undefined ? {} : { picture: patch.picture ?? undefined }),
    ...(patch.description === undefined ? {} : { description: patch.description }),
    ...(patch.onboardingPending === undefined ? {} : { onboardingPending: false }),
    updatedAt,
  };
  const tableName = getLinkedProfilesTableName();
  if (!tableName) {
    localProfiles.set(subject, updatedProfile);
    return toPublicProfile(updatedProfile);
  }

  const setParts = ['#updatedAt = :updatedAt'];
  const removeParts: string[] = [];
  const names: Record<string, string> = { '#updatedAt': 'updatedAt', '#status': 'status' };
  const values: Record<string, unknown> = { ':updatedAt': updatedAt, ':active': 'active' };
  if (patch.displayName !== undefined) {
    setParts.push('#displayName = :displayName');
    names['#displayName'] = 'displayName';
    values[':displayName'] = patch.displayName;
  }
  if (patch.picture !== undefined) {
    if (patch.picture === null) {
      // Remove the optional picture in the same conditional write as every other field.
      removeParts.push('#picture');
      names['#picture'] = 'picture';
    } else {
      setParts.push('#picture = :picture');
      names['#picture'] = 'picture';
      values[':picture'] = patch.picture;
    }
  }
  if (patch.description !== undefined) {
    setParts.push('#description = :description');
    names['#description'] = 'description';
    values[':description'] = patch.description;
  }
  if (patch.onboardingPending !== undefined) {
    setParts.push('#onboardingPending = :onboardingPending');
    names['#onboardingPending'] = 'onboardingPending';
    values[':onboardingPending'] = false;
  }

  const updateExpressions = [`SET ${setParts.join(', ')}`];
  if (removeParts.length > 0) updateExpressions.push(`REMOVE ${removeParts.join(', ')}`);
  const result = await getDocumentClient().send(new UpdateCommand({
    TableName: tableName,
    Key: { pk: current.pk, sk: current.sk },
    UpdateExpression: updateExpressions.join(' '),
    ConditionExpression: '#status = :active',
    ExpressionAttributeNames: names,
    ExpressionAttributeValues: values,
    ReturnValues: 'ALL_NEW',
  }));
  return toPublicProfile(result.Attributes as StoredProfile);
}

/** Resolves a signed session cookie and its active canonical profile. */
export async function resolveActiveProfile(
  event: ProfileRequestEvent,
): Promise<ProfileResolution> {
  let config;
  try {
    config = getGoogleAuthConfig();
  } catch (error) {
    if (error instanceof AuthConfigurationError) {
      throw new ProfileRequestError(503, 'AUTH_CONFIGURATION_ERROR', 'Authentication is not configured');
    }
    throw error;
  }

  const cookieHeader = event.cookies?.join('; ')
    || Object.entries(event.headers ?? {})
      .find(([name]) => name.toLowerCase() === 'cookie')?.[1]
    || '';
  const cookieValue = cookieHeader.match(/(?:^|;\s*)atlas_session=([^;]+)/)?.[1];
  const session = cookieValue ? verifyAtlasSessionCookie(cookieValue, config.sessionSecret) : undefined;
  if (!session) {
    throw new ProfileRequestError(401, 'SESSION_REQUIRED', 'Authentication required');
  }

  const profile = await getProfileBySubject(session.subject);
  if (!profile) throw new ProfileRequestError(404, 'PROFILE_NOT_FOUND', 'Profile not found');
  if (profile.status !== 'active') throw new ProfileRequestError(403, 'PROFILE_INACTIVE', 'Profile is inactive');
  return { profile, session };
}

/** Records profile lifecycle events without exposing credential material. */
export async function recordProfileEvent(
  action: 'profile_created' | 'onboarding_completed',
  subject: string,
): Promise<void> {
  await recordAccessEvent({
    action,
    result: 'accepted',
    actorSubject: subject,
    targetSubject: subject,
  });
}
