import { randomUUID } from 'node:crypto';
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocumentClient, PutCommand } from '@aws-sdk/lib-dynamodb';

/**
 * AuthenticationAudit — Records login outcomes without persisting credentials.
 *
 * In a deployed function, the linked Audit table receives the event. Local
 * development without a linked table falls back to a safe structured log.
 */

/** Safe audit event for successful and rejected authentication attempts. */
export interface AuthenticationAuditEvent {
  action: 'login' | 'login_rejected';
  result: 'accepted' | 'rejected';
  subject?: string;
  reason?: string;
}

/** Safe audit event shared by authentication and profile lifecycle operations. */
export interface AccessAuditEvent {
  action: 'profile_created' | 'onboarding_completed';
  result: 'accepted';
  actorSubject: string;
  targetSubject: string;
}

/** Writes one authentication event to the linked audit table or local safe logs. */
export async function recordAuthenticationEvent(event: AuthenticationAuditEvent): Promise<void> {
  await writeAuditEvent({
    type: 'authentication',
    pk: `AUTH#${event.subject ?? 'UNKNOWN'}`,
    skPrefix: 'LOGIN',
    ...event,
  });
}

/** Writes one profile lifecycle event without storing tokens or request payloads. */
export async function recordAccessEvent(event: AccessAuditEvent): Promise<void> {
  await writeAuditEvent({
    type: 'profile_access',
    pk: `PROFILE#${event.targetSubject}`,
    skPrefix: event.action.toUpperCase(),
    ...event,
  });
}

/** Persists a safe audit record or logs it when no local table is linked. */
async function writeAuditEvent(event: Record<string, unknown> & { pk: string; skPrefix: string }): Promise<void> {
  const auditTableName = getLinkedAuditTableName();
  const timestamp = new Date().toISOString();
  const { skPrefix, pk, ...safeEvent } = event;
  const item = {
    pk,
    sk: `${skPrefix}#${timestamp}#${randomUUID()}`,
    ...safeEvent,
    timestamp,
    expiresAt: Math.floor(Date.now() / 1000) + 60 * 60 * 24 * 730,
  };

  // Local fallback: preserve observable audit evidence without pretending persistence exists.
  if (!auditTableName) {
    console.info('Access audit event', item);
    return;
  }

  const client = DynamoDBDocumentClient.from(new DynamoDBClient({}));
  await client.send(new PutCommand({
    TableName: auditTableName,
    Item: item,
  }));
}

/** Reads the table name generated by SST's linked Audit resource. */
function getLinkedAuditTableName(): string | undefined {
  const rawResource = process.env.SST_RESOURCE_Audit;
  if (!rawResource) return undefined;

  try {
    const resource = JSON.parse(rawResource) as { tableName?: unknown };
    return typeof resource.tableName === 'string' && resource.tableName.length > 0
      ? resource.tableName
      : undefined;
  } catch {
    return undefined;
  }
}
