import { randomUUID } from 'node:crypto';
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocumentClient, PutCommand } from '@aws-sdk/lib-dynamodb';

/**
 * AuthenticationAudit — Records login outcomes without persisting credentials.
 *
 * In a deployed function, the linked Audit table receives the event. Local
 * development without a linked table falls back to a safe structured log.
 */

/** Safe audit event for successful and rejected authentication attempts. */
export interface AuthenticationAuditEvent {
  action: 'login' | 'login_rejected';
  result: 'accepted' | 'rejected';
  subject?: string;
  reason?: string;
}

/** Writes one authentication event to the linked audit table or local safe logs. */
export async function recordAuthenticationEvent(event: AuthenticationAuditEvent): Promise<void> {
  const auditTableName = getLinkedAuditTableName();
  const timestamp = new Date().toISOString();
  const safeEvent = {
    ...event,
    timestamp,
    expiresAt: Math.floor(Date.now() / 1000) + 60 * 60 * 24 * 730,
  };

  // Local fallback: preserve observable audit evidence without pretending persistence exists.
  if (!auditTableName) {
    console.info('Authentication audit event', safeEvent);
    return;
  }

  const client = DynamoDBDocumentClient.from(new DynamoDBClient({}));
  await client.send(new PutCommand({
    TableName: auditTableName,
    Item: {
      pk: `AUTH#${event.subject ?? 'UNKNOWN'}`,
      sk: `LOGIN#${timestamp}#${randomUUID()}`,
      type: 'authentication',
      ...safeEvent,
    },
  }));
}

/** Reads the table name generated by SST's linked Audit resource. */
function getLinkedAuditTableName(): string | undefined {
  const rawResource = process.env.SST_RESOURCE_Audit;
  if (!rawResource) return undefined;

  try {
    const resource = JSON.parse(rawResource) as { tableName?: unknown };
    return typeof resource.tableName === 'string' && resource.tableName.length > 0
      ? resource.tableName
      : undefined;
  } catch {
    return undefined;
  }
}
